# Generated by Django 5.1 on 2024-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('isbn', models.CharField(max_length=13, verbose_name='Shabak Serial')),
                ('date_published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_edited', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
